final class FilterConstants {
    private init() {}

    static let speciesGroupId = "species"
    static let genderGroupId = "gender"
    static let statusGroupId = "status"
    static let speciesHuman = "human"
    static let speciesAlien = "alien"
    static let speciesRobot = "robot"
    static let speciesAnimal = "animal"
    static let speciesDisease = "disease"
    static let speciesCronenberg = "cronenberg"
    static let speciesPoopybutthole = "poopybutthole"
    static let speciesMythological = "mythological"
    static let unknown = "unknown"
    static let genderFemale = "female"
    static let genderMale = "male"
    static let genderGenderless = "genderless"
    static let statusAlive = "alive"
    static let statusDead = "dead"
    static let speciesHumanQuery = "Human"
    static let speciesAlienQuery = "Alien"
    static let speciesRobotQuery = "Robot"
    static let speciesAnimalQuery = "Animal"
    static let speciesDiseaseQuery = "Disease"
    static let speciesCronenbergQuery = "Cronenberg"
    static let speciesPoopybuttholeQuery = "Poopybutthole"
    static let speciesMythologicalQuery = "Mythological Creature"
    static let genderFemaleQuery = "Female"
    static let genderMaleQuery = "Male"
    static let genderGenderlessQuery = "Genderless"
    static let statusAliveQuery = "Alive"
    static let statusDeadQuery = "Dead"
}
